Repository GSG-G9/ws-booker, pull requests merged in 2021-04, with the labels that each got.

#49 Firebase Authentication
  package-lock.json
  package.json
  src/App/index.js
  src/firebase/config.js
  src/firebase/context.js
Labels: Done

#50 CardContainer
  src/assets/icons/arrow.svg
  src/components/CommonComponents/CardContainer/index.js
  src/components/CommonComponents/CardContainer/style.css
Labels: Done

#64 Get user by id
  src/firebase/firestore/user/getUserById.js
  src/firebase/firestore/user/index.js
Labels: Done

#63 Get workspace by id
  src/firebase/config.js
  src/firebase/firestore.js
  src/firebase/firestore/workspace/getWorkspaceById.js
  src/firebase/firestore/workspace/index.js
Labels: Awaiting Review

#69 Add workspace
  src/firebase/firestore/workspace/addWorkspace.js
  src/firebase/firestore/workspace/index.js
  src/utils/validation/index.js
  src/utils/validation/workspaceSchema.js
Labels: Done

#65 Get All Workspaces
  src/firebase/firestore/workspace/getAllWorkspaces.js
  src/firebase/firestore/workspace/index.js
Labels: Done

#68 Delete Workspace
  src/firebase/firestore/workspace/DeleteWorkspace.js
  src/firebase/firestore/workspace/index.js
Labels: Done

#35 header
  src/assets/images/WSBooker.png
  src/assets/images/profile-user.png
  src/components/CommonComponents/Button/index.js
  src/components/Layout/Header/index.js
  src/components/Layout/Header/style.css
Labels: Done

#73 Edit workspace rating
  src/firebase/firestore/workspace/addWorkspace.js
  src/firebase/firestore/workspace/editWorkspaceRating.js
  src/firebase/firestore/workspace/index.js
  src/utils/validation/index.js
  src/utils/validation/workspaceRatingSchema.js
  src/utils/validation/workspaceSchema.js
Labels: Done

#77 75 add user
  src/firebase/firestore/user/addUser.js
  src/firebase/firestore/user/index.js
Labels: Done

#71 Edit workspace data by admin
  src/firebase/firestore/workspace/editWorkspace.js
  src/firebase/firestore/workspace/index.js
Labels: Done

#67 Edit User Data
  src/firebase/firestore/user/EditUserData.js
  src/firebase/firestore/user/index.js
  src/utils/validation/index.js
  src/utils/validation/userSchema.js
Labels: Done

#78 Get booking by user
  src/firebase/firestore/booking/getBookingByUserId.js
  src/firebase/firestore/booking/index.js
Labels: Awaiting Review

#85 Fix get booking by user id
  src/firebase/firestore/booking/getBookingByUserId.js
Labels: Done

#87 about page
  src/assets/images/about_cover.png
  src/pages/About/index.js
  src/pages/About/style.css
Labels: Done

#81 Signin with google
  src/App/index.js
  src/Login/loginWithGoogle.js
  src/assets/images/profile-user.png
  src/components/CommonComponents/Button/index.js
  src/components/CommonComponents/Loader/index.js
  src/components/Layout/Header/index.js
  src/components/Layout/Header/style.css
  src/firebase/context.js
  src/firebase/firestore/user/addUser.js
Labels: Done

#80 Delete booking
  src/firebase/firestore/booking/deleteBooking.js
  src/firebase/firestore/booking/getBookingByUserId.js
  src/firebase/firestore/booking/index.js
Labels: Done

#79 post Booking
  package-lock.json
  package.json
  src/firebase/firestore/booking/addBooking.js
  src/firebase/firestore/booking/getBookingByDate.js
  src/firebase/firestore/booking/getBookingByWorkspaceId.js
  src/firebase/firestore/booking/index.js
  src/firebase/firestore/booking/postBooking.js
  src/pages/WorkSpaceProfile/index.js
  src/pages/WorkSpaceProfile/style.css
  src/utils/checkOverlap.js
  src/utils/index.js
  src/utils/validation/bookingSchema.js
  src/utils/validation/index.js
Labels: Done, priority-2

#86 Workspace profile page
  src/pages/WorkSpaceProfile/index.js
  src/pages/WorkSpaceProfile/style.css
Labels: Awaiting Review, priority-2

#91 Fix workspace profile page style
  src/pages/WorkSpaceProfile/style.css
Labels: Done

#84 Landing page
  .firebase/hosting.YnVpbGQ.cache
  .firebaserc
  firebase.json
  package-lock.json
  package.json
  src/App/index.js
  src/assets/images/homeheader.jpg
  src/components/CommonComponents/Button/index.js
  src/components/CommonComponents/CardContainer/index.js
  src/components/CommonComponents/CardContainer/style.css
  src/components/CommonComponents/FeaturesCard/style.css
  src/components/CommonComponents/Input/index.js
  src/components/CommonComponents/WorkspaceCard/index.js
  src/components/CommonComponents/WorkspaceCard/style.css
  src/components/HomeHeader/index.js
  src/components/HomeHeader/style.css
  src/components/Layout/Footer/style.css
  src/firebase/firestore/workspace/getAllWorkspaces.js
  src/pages/HomePage/index.js
  src/pages/HomePage/style.css
  src/utils/createSearchUrl.js
  src/utils/index.js
  src/utils/validation/workspaceSchema.js
Labels: Done, priority-1

#92 Fix ant rate class
  src/pages/WorkSpaceProfile/index.js
  src/pages/WorkSpaceProfile/style.css
Labels: Done

#88 Search results & Top rated & newest pages
  src/components/CommonComponents/CardContainer/index.js
  src/components/CommonComponents/CardContainer/style.css
  src/components/HomeHeader/style.css
  src/firebase/firestore/workspace/getSearchResults.js
  src/firebase/firestore/workspace/index.js
  src/pages/HomePage/index.js
  src/pages/NewestWorkspaces/index.js
  src/pages/NewestWorkspaces/style.css
  src/pages/SearchResults/index.js
  src/pages/SearchResults/style.css
  src/pages/TopRatedWorkspaces/index.js
  src/pages/TopRatedWorkspaces/style.css
  src/utils/validation/index.js
  src/utils/validation/searchSchema.js
Labels: Awaiting Review

#96 Protected and Admin Routes
  src/App/Routes/AdminRoutes.js
  src/App/Routes/ProtectedRoutes.js
  src/App/Routes/index.js
  src/App/index.js
  src/components/CommonComponents/CardContainer/index.js
  src/firebase/context.js
Labels: Done

#99 handled profile nav link for logged in users
  src/components/Layout/Header/index.js
Labels: Done

#89 Layout page
  package-lock.json
  src/App/index.js
  src/firebase/firestore/workspace/getSearchResults.js
  src/pages/Layout/index.js
  src/pages/Layout/style.css
  src/pages/WorkSpaceProfile/style.css
  src/pages/index.js
Labels: Done

#101 Modified workspace card style
  src/components/CommonComponents/WorkspaceCard/index.js
  src/components/CommonComponents/WorkspaceCard/style.css
Labels: Awaiting Review

#83 user profile
  .eslintrc.json
  src/assets/icons/edit.svg
  src/assets/icons/email.svg
  src/assets/icons/phone.svg
  src/assets/images/backgound_cover.png
  src/assets/images/user.png
  src/components/CommonComponents/Input/index.js
  src/components/CommonComponents/WorkspaceCard/index.js
  src/firebase/config.js
  src/firebase/firestore/user/EditUserData.js
  src/index.js
  src/pages/UserProfile/index.js
  src/pages/UserProfile/style.css
  src/pages/WorkSpaceProfile/index.js
  src/utils/validation/userSchema.js
Labels: Done

#90 Booking modal
  src/components/CommonComponents/FeaturesCard/index.js
  src/components/CommonComponents/FeaturesCard/style.css
  src/components/CommonComponents/Input/index.js
  src/components/CommonComponents/WorkspaceCard/index.js
  src/context/AuthContext.js
  src/firebase/context.js
  src/firebase/firestore/booking/addBooking.js
  src/firebase/firestore/booking/postBooking.js
  src/firebase/firestore/user/EditUserData.js
  src/firebase/firestore/user/addUser.js
  src/firebase/firestore/user/editUserCanBook.js
  src/firebase/firestore/user/index.js
  src/pages/UserProfile/index.js
  src/pages/WorkSpaceProfile/index.js
  src/pages/WorkSpaceProfile/style.css
  src/utils/validation/canBookSchema.js
  src/utils/validation/index.js
Labels: Done

#105 Not Found page
  src/assets/images/oops.png
  src/pages/NotFound/index.js
  src/pages/NotFound/style.css
Labels: Done

#113 fix bug - Search page
  src/pages/SearchResults/style.css
Labels: Done

#114 fix bug - user profile
  src/pages/UserProfile/index.js
Labels: Done

#117 Fix - landing page
  .firebase/hosting.YnVpbGQ.cache
  src/assets/icons/add.svg
  src/assets/icons/list.svg
  src/assets/icons/logout.svg
  src/assets/images/homeheader1.png
  src/components/CommonComponents/CardContainer/index.js
  src/components/CommonComponents/WorkspaceCard/index.js
  src/components/CommonComponents/WorkspaceCard/style.css
  src/components/HomeHeader/style.css
  src/firebase/context.js
  src/pages/DashboardAddWorkspace/index.js
Labels: Done

#118 Fix user image and name
  src/components/Layout/Header/index.js
  src/components/Layout/Header/style.css
  src/firebase/context.js
  src/pages/UserProfile/index.js
Labels: Done

#119 Fix footer style
  src/components/Layout/Footer/style.css
  src/pages/Layout/index.js
  src/pages/Layout/style.css
Labels: Done

#115 fix bug - Amenities fram
  src/assets/icons/check.svg
  src/assets/icons/favicon.ico
  src/assets/icons/pin.svg
  src/pages/WorkSpaceProfile/index.js
  src/pages/WorkSpaceProfile/style.css
Labels: Done

#116 Fix bug | booking modal
  src/pages/WorkSpaceProfile/index.js
Labels: Done

#94 Dashboard all workspaces
  .eslintrc.json
  package-lock.json
  package.json
  src/App/Routes/AdminRoutes.js
  src/components/CommonComponents/CardContainer/index.js
  src/components/HomeHeader/style.css
  src/firebase/context.js
  src/firebase/firestore/workspace/getSearchResults.js
  src/pages/DashboardAllWorkspaces/index.js
  src/pages/DashboardAllWorkspaces/style.css
Labels: Done

#120 Fix case sensitive search
  src/App/index.js
  src/firebase/firestore/workspace/addWorkspace.js
  src/firebase/firestore/workspace/fetchSearchResults.js
  src/firebase/firestore/workspace/getSearchResults.js
  src/firebase/firestore/workspace/index.js
  src/pages/SearchResults/index.js
Labels: Done

#93 Dashboard AddWorkspace
  src/components/CommonComponents/AdminNav/index.js
  src/components/CommonComponents/AdminNav/style.css
  src/firebase/firestore/workspace/addWorkspace.js
  src/pages/DashboardAddWorkspace/index.js
  src/pages/DashboardAddWorkspace/style.css
  src/pages/DashboardAllWorkspaces/index.js
  src/pages/DashboardAllWorkspaces/style.css
Labels: Awaiting Review

#122 Handling booking capacity
  package-lock.json
  src/firebase/firestore/booking/postBooking.js
Labels: Awaiting Review

#126 Display user booking info
  src/pages/UserProfile/index.js
  src/pages/UserProfile/style.css
Labels: Done

#124 Fix Readme
  README.md
Labels: Done

#129 Fix cancel book button
  src/components/CommonComponents/WorkspaceCard/index.js
  src/pages/UserProfile/index.js
Labels: Done

#130 Modified booking modal style
  src/components/CommonComponents/AdminNav/style.css
  src/components/CommonComponents/WorkspaceCard/index.js
  src/components/Layout/Footer/index.js
  src/components/Layout/Footer/style.css
  src/pages/Layout/index.js
  src/pages/Layout/style.css
  src/pages/NotFound/index.js
  src/pages/UserProfile/index.js
  src/pages/WorkSpaceProfile/index.js
  src/pages/WorkSpaceProfile/style.css
Labels: Done

#127 Rating
  src/components/CommonComponents/Rating/index.js
  src/firebase/firestore/rating/addRating.js
  src/firebase/firestore/rating/getRatingByWorkspaceId.js
  src/firebase/firestore/rating/index.js
  src/firebase/firestore/workspace/editWorkspaceRating.js
  src/pages/WorkSpaceProfile/index.js
  src/pages/WorkSpaceProfile/style.css
  src/utils/validation/addRatingSchema.js
  src/utils/validation/index.js
Labels: Done
